version: '3'

services:
  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    expose:
      - 8090
    ports:
      - 80:8090
    depends_on:
      - python
  python:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 8080
    ports:
      - 8080:8080
    command: "gunicorn -b 0.0.0.0:8080 --reload --chdir /usr/src/app/vk_auth wsgi:application"